/** Extra kit/legacy regression coverage against production build. */
import {createRequire} from 'node:module';import {writeFileSync,readFileSync} from 'node:fs';
const require=createRequire('D:/Claude-projects/b2b-dssl/package.json');const browser=await require('playwright').chromium.launch({executablePath:'C:/Users/kanar/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe'});
const base='http://127.0.0.1:4340';const results=[],failures=[];
const kitOnly=process.argv.includes('--kit-only');
if(kitOnly)results.push(...JSON.parse(readFileSync('tasks/portfolio-rebuild/common/support-verification.json')).results.filter(r=>r.route!=='/kit/'));
const profiles=[{width:1440,height:900},{width:1024,height:900},{width:390,height:844},{width:360,height:800},{width:1440,height:600}];
const read=p=>p.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,booted:window.__dsMotionBooted,pins:document.querySelectorAll('.pin-spacer').length,blank:[...document.querySelectorAll('[data-h="thesis"],[data-h="para"]')].filter(e=>e.getClientRects().length&&+getComputedStyle(e).opacity===0).length,broken:[...document.images].filter(e=>e.getClientRects().length&&(!e.complete||!e.naturalWidth)).map(e=>e.currentSrc||e.src),lang:document.documentElement.lang,title:document.querySelector('h1')?.textContent,newStory:!!document.querySelector('[data-story-version]'),robots:document.querySelector('meta[name="robots"]')?.content}));
try{
for(const mode of ['full','reduce','no-js'])for(const viewport of profiles){
const c=await browser.newContext({viewport,reducedMotion:mode==='full'?'no-preference':'reduce',javaScriptEnabled:mode!=='no-js'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/kit/',{waitUntil:'networkidle'});await p.waitForTimeout(1200);const height=await p.evaluate(()=>document.documentElement.scrollHeight);for(let y=0;y<height;y+=650){await p.evaluate(y=>scrollTo(0,y),y);await p.waitForTimeout(mode==='full'?100:30);}
// Visit off-screen carousel slides before asserting lazy media availability.
for(const track of await p.locator('[data-carousel-track]').all()){await track.scrollIntoViewIfNeeded();await track.evaluate(e=>e.scrollLeft=e.scrollWidth);await p.waitForTimeout(300);await track.evaluate(e=>e.scrollLeft=0);}
await p.waitForTimeout(1500);const state=await read(p);results.push({route:'/kit/',mode,...viewport,...state,errors});if(errors.length||state.overflow>0||state.broken.length||state.blank||!state.robots?.includes('noindex')||(mode==='full'&&!state.booted)||(mode!=='full'&&state.pins))failures.push(results.at(-1));await c.close();}
if(!kitOnly)for(const lang of ['en','ru'])for(const slug of ['agent-ops-console','partner-portal','learn','vet-clinic','pawly'])for(const width of [1440,390]){
const c=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const route=`/${lang==='ru'?'ru/':''}work/${slug}/`;await p.goto(base+route,{waitUntil:'networkidle'});const height=await p.evaluate(()=>document.documentElement.scrollHeight);for(let y=0;y<height;y+=650){await p.evaluate(y=>scrollTo(0,y),y);await p.waitForTimeout(30);}await p.waitForTimeout(250);const state=await read(p);results.push({route,width,...state,errors});if(errors.length||state.overflow>0||state.broken.length||state.blank||state.newStory||!state.title||state.lang!==lang)failures.push(results.at(-1));await c.close();}
}finally{await browser.close();}writeFileSync('tasks/portfolio-rebuild/common/support-verification.json',JSON.stringify({base,results,failures},null,2));console.log({profiles:results.length,failures:failures.length});if(failures.length)throw new Error('Support regression failed');
