import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import path from 'node:path';
const require=createRequire('d:/Claude-projects/Agent-ops-console/package.json');
const {chromium}=require('playwright');
export const root=path.resolve('tasks/robert-review-2026-10-07/project-sweep');
export const base='http://127.0.0.1:4420';
export const routes=['about','work/agent-ops-console','work/partner-portal','work/learn','work/vet-clinic','work/pawly','404'];
export const urlFor=(route,loc)=>`${base}/${loc==='ru'?'ru/':''}${route}${route==='404'?'':'/'}`;
export const launch=()=>chromium.launch({executablePath:'C:/Users/kanar/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe'});
export async function settle(p){await p.addStyleTag({content:'astro-dev-toolbar{display:none!important}'});await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(3000);await p.evaluate(async()=>{for(let y=0;y<document.documentElement.scrollHeight;y+=400){scrollTo(0,y);await new Promise(r=>setTimeout(r,100));}scrollTo(0,0);});await p.waitForTimeout(2000);}
export function collect(){
 const cid={}; for(const s of document.querySelectorAll('style[data-vite-dev-id]')){let f=s.getAttribute('data-vite-dev-id').split('?')[0].replaceAll('\\','/');for(const m of s.textContent.matchAll(/data-astro-cid-([\w]+)/g))cid[`data-astro-cid-${m[1]}`]=f.replace(/^.*\/src\//,'src/');}
 const component=e=>{for(let a=e;a;a=a.parentElement){if(a.hasAttribute('data-astro-source-file'))return a.getAttribute('data-astro-source-file');for(const k of a.getAttributeNames())if(cid[k]&&!cid[k].includes('/pages/'))return cid[k];}return 'unmapped';};
 const rect=e=>{const r=e.getBoundingClientRect();return{x:Math.round(r.x),y:Math.round(r.y+scrollY),w:Math.round(r.width),h:Math.round(r.height)};};
 const visible=e=>{let s=getComputedStyle(e),r=e.getBoundingClientRect();return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'&&!e.closest('astro-dev-toolbar,svg,dialog:not([open])')};
 const sel=e=>e.id?`#${e.id}`:e.tagName.toLowerCase()+[...e.classList].slice(0,3).map(c=>'.'+c).join('');
 const info=e=>({text:(e.innerText||e.textContent||'').trim().replace(/\s+/g,' ').slice(0,160),selector:sel(e),component:component(e),rect:rect(e)});
 const els=[...document.querySelectorAll('body *')].filter(visible);
 const leaves=els.filter(e=>[...e.childNodes].some(n=>n.nodeType===3&&n.textContent.trim())&&!e.closest('script,style,noscript'));
 const headings=els.filter(e=>/^H[1-4]$/.test(e.tagName)||[...e.classList].some(c=>c.startsWith('ds-heading-'))).map(e=>({...info(e),tag:e.tagName,size:parseFloat(getComputedStyle(e).fontSize),weight:getComputedStyle(e).fontWeight,lineHeight:getComputedStyle(e).lineHeight}));
 const candidates=[];const push=(cls,e,detail)=>candidates.push({cls,...info(e),detail});
 const glyph=/[\u2190-\u21FF\u2300-\u23FF\u25A0-\u27BF\u{1F300}-\u{1FAFF}\uFE0F©®™‖✓✔]/u;
 const status=/concept|концепт|pet[- ]?project|пет-проект|учебн\S* проект|hypothesis|гипотез|demo|демо|demonstration|демонстрац|reconstruction|реконструкц|reinterpret|переосмысл|not live|not deployed|не внедр|лишь прототип|only a prototype|not a real|не настоящ/iu;
 for(const e of leaves){const s=getComputedStyle(e),t=[...e.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join(' ').trim(),size=parseFloat(s.fontSize),ls=parseFloat(s.letterSpacing)||0;
  if(/mono/i.test(s.fontFamily)||(size<=13&&ls/size>.04&&(s.textTransform==='uppercase'||t===t.toUpperCase()&&/[A-ZА-Я]/.test(t)))||/^\d{2}\b/.test(t)||t.split('·').length>=3)push('T1',e,{font:s.fontFamily,size,spacing:ls,transform:s.textTransform});
  if(glyph.test(t))push('T3',e,{field:'text',value:t});
  if(document.documentElement.lang.startsWith('en')&&/[А-Яа-яЁё]/.test(t)||document.documentElement.lang.startsWith('ru')&&/(?:[A-Za-z][\w-]*\s+){2}[A-Za-z][\w-]*/.test(t))push('X1',e,{value:t});
  if(status.test(t))push('X2',e,{field:'text',value:t});
  if(/copy|click to|нажмите|копир|‖|▶/i.test(t))push('T4',e,{value:t});
 }
 for(const e of [...document.querySelectorAll('[alt],[aria-label],[title],meta,script[type="application/ld+json"]')]){for(const a of ['alt','aria-label','title','content']){const t=e.getAttribute(a);if(t&&glyph.test(t))push('T3',e,{field:a,value:t});if(t&&status.test(t))push('X2',e,{field:a,value:t});}if(e.tagName==='SCRIPT'&&status.test(e.textContent))push('X2',e,{field:'JSON-LD',value:e.textContent});}
 const transparent=s=>s==='rgba(0, 0, 0, 0)'||s==='transparent';
 // CIELAB D65; ΔE76 comparison of the nearest opaque scene and body.
 const lab=color=>{let a=(color.match(/[\d.]+/g)||[]).slice(0,3).map(v=>{v=Number(v)/255;return v>.04045?((v+.055)/1.055)**2.4:v/12.92;});if(a.length<3)return null;let [r,g,b]=a;let xyz=[(r*.4124564+g*.3575761+b*.1804375)/.95047,r*.2126729+g*.7151522+b*.072175,(r*.0193339+g*.119192+b*.9503041)/1.08883].map(v=>v>.008856?Math.cbrt(v):7.787*v+16/116);return[116*xyz[1]-16,500*(xyz[0]-xyz[1]),200*(xyz[1]-xyz[2])];};
 const bg=e=>{for(let a=e;a;a=a.parentElement){let c=getComputedStyle(a).backgroundColor;if(!transparent(c))return c;}return'rgb(255, 255, 255)';};
 const media=els.filter(e=>/^(IMG|VIDEO|IFRAME|CANVAS)$/.test(e.tagName)).map(e=>{const s=getComputedStyle(e),own=rect(e),back=bg(e.parentElement),bl=lab(bg(document.body)),ml=lab(back),delta=bl&&ml?Math.hypot(...bl.map((v,i)=>v-ml[i])):null;
  if(delta!==null&&delta<3&&parseFloat(s.borderTopWidth)===0&&s.boxShadow==='none')push('C2',e,{background:back,body:bg(document.body),deltaE:delta});
  for(let a=e.parentElement,n=0;a&&n<4;a=a.parentElement,n++){const x=getComputedStyle(a),r=rect(a),padding=Math.max(...['paddingTop','paddingBottom','paddingLeft','paddingRight'].map(k=>parseFloat(x[k]))),ratio=own.w*own.h/(r.w*r.h);const es=getComputedStyle(e.parentElement);if(padding>=12&&ratio>=.7&&(!transparent(x.backgroundColor)||parseFloat(x.borderTopWidth)>0)&&(parseFloat(s.borderRadius)>0||parseFloat(s.borderTopWidth)>0||parseFloat(es.borderRadius)>0||parseFloat(es.borderTopWidth)>0))push('C1',a,{padding,ratio,background:x.backgroundColor,border:x.borderTopWidth,depth:n,media:info(e)});}
  return{...info(e),src:e.currentSrc||e.src,alt:e.alt,background:back};});
 for(const e of els){const s=getComputedStyle(e),r=rect(e);if((e.tagName==='HR'||parseFloat(s.borderTopWidth)>=1||parseFloat(s.borderBottomWidth)>=1)&&e.parentElement&&r.w>=rect(e.parentElement).w*.5&&!e.closest('button,a'))push('L5',e,{top:s.borderTopWidth,bottom:s.borderBottomWidth});
  for(const pseudo of ['::before','::after']){const content=getComputedStyle(e,pseudo).content;if(content&&content!=='none'&&glyph.test(content))push('T3',e,{field:pseudo,value:content});}
  if(/grid|flex/.test(s.display)){const ch=[...e.children].filter(visible).filter(a=>a.matches('img,picture,figure')||a.querySelector('img,picture,video')||/card/.test(a.className));if(ch.length>=2){const rr=ch.map(rect);const tops=rr.map(a=>a.y),spread=Math.max(...tops)-Math.min(...tops);if(innerWidth>1000&&spread>8)push('L1',e,{spread,children:ch.map(info),sameRow:rr.every(a=>a.y<Math.min(...rr.map(x=>x.y+x.h)))});}}
  if(innerWidth===360&&r.x+r.w>innerWidth+1&&r.w>0)push('R1',e,{kind:'right-edge',right:r.x+r.w});
  if(s.overflow==='hidden'&&e.scrollWidth>e.clientWidth+1&&leaves.includes(e))push('R1',e,{kind:'clipped-text',scrollWidth:e.scrollWidth,clientWidth:e.clientWidth});
 }
 const links=els.filter(e=>e.matches('a,button')).map(e=>{const s=getComputedStyle(e),label=e.querySelector('.ds-link__label'),l=label?getComputedStyle(label):s;const item={...info(e),tag:e.tagName,href:e.getAttribute('href'),decoration:s.textDecorationLine,labelDecoration:l.textDecorationLine,border:s.borderBottomWidth,background:s.backgroundImage,svg:!!e.querySelector('svg'),inline:!!e.closest('p'),variant:e.className};if(!item.inline&&(s.textDecorationLine.includes('underline')||l.textDecorationLine.includes('underline')||parseFloat(s.borderBottomWidth)>0))push('K1',e,item);if(innerWidth===360&&rect(e).h<44)push('R1',e,{kind:'small-target',height:rect(e).h,inline:item.inline});return item;});
 const sections=els.filter(e=>e.matches('main section')).map(e=>{const small=leaves.filter(a=>a.closest('section')===e&&parseFloat(getComputedStyle(a).fontSize)<=14);if(small.length>6)push('T2',e,{count:small.length,small:small.map(info)});return{...info(e),smallCount:small.length};});
 const overlap=(a,b)=>{let x=new Set(a.toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]),y=new Set(b.toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]);return x.size?[...x].filter(w=>y.has(w)).length/x.size:0;};
 for(const e of leaves.filter(a=>a.matches('figcaption,[class*=caption],[class*=eyebrow]'))){let n=e.parentElement.querySelector('h1,h2,h3,p:not([class*=caption])');if(n&&n!==e&&overlap(e.innerText,n.innerText)>=.7)push('T2',e,{kind:'duplicate-caption',neighbor:info(n)});}
 for(const e of els.filter(a=>a.matches('h1,h2,h3'))){let next=e.nextElementSibling;while(next&&!visible(next))next=next.nextElementSibling;if(next){let gap=rect(next).y-rect(e).y-rect(e).h,size=parseFloat(getComputedStyle(e).fontSize);if(size>=48&&gap<32)push('L2',e,{kind:'heading-gap',gap,size,next:info(next)});}}
 const gaps=[];for(let i=1;i<sections.length;i++){let prev=sections[i-1],cur=sections[i];gaps.push({before:prev.selector,after:cur.selector,gap:cur.rect.y-prev.rect.y-prev.rect.h});}const positive=gaps.map(g=>g.gap).filter(g=>g>0).sort((a,b)=>a-b),median=positive[Math.floor(positive.length/2)];for(const g of gaps)if(median&&g.gap>median*2)candidates.push({cls:'L2',component:'page-layout',selector:g.after,text:'section gap',detail:{...g,median}});
 const inventory={};for(const [attr,f] of Object.entries(cid)){const roots=[...document.querySelectorAll(`[${attr}]`)].filter(e=>!e.parentElement?.hasAttribute(attr));if(roots.length)inventory[f]=(inventory[f]||0)+roots.length;}
 const years=leaves.filter(e=>/\b20\d\d\b/.test(e.innerText)).map(info);
 const copy=[...document.querySelectorAll('main section')].filter(visible).map(e=>({selector:sel(e),text:e.innerText,alt:[...e.querySelectorAll('img[alt]')].map(x=>x.alt)}));
 const editorial=document.querySelector('.case-story')?.innerText||document.querySelector('main')?.innerText||'';
 const text=editorial.replace(/\s+/g,' ').trim();
 return{lang:document.documentElement.lang,title:document.title,inventory,candidates,headings,links,media,sections,gaps,years,copy,editorial:text,wordCount:(text.match(/[\p{L}\p{N}]+(?:['’-][\p{L}\p{N}]+)*/gu)||[]).length,bodyWidth:document.documentElement.scrollWidth,viewport:innerWidth,publicLinks:links.filter(x=>/\/(preview|kit|500)(\/|\.|$)/.test(x.href||'')),cid};
}
async function setup(){const b=await launch(),p=await b.newPage({viewport:{width:1440,height:900}}),data=[];for(const loc of ['en','ru'])for(const route of routes){const response=await p.goto(urlFor(route,loc),{waitUntil:'networkidle'});const d=await p.evaluate(collect);data.push({route,loc,status:response.status(),inventory:d.inventory});}await b.close();await fs.writeFile(path.join(root,'logs/setup.json'),JSON.stringify(data,null,2));let components=[...new Set(data.flatMap(d=>Object.keys(d.inventory)))].filter(f=>/components\/(Case|Media|Screen|Decision|Note|Meta|More|Prose)/.test(f));let rows=components.map(f=>`| ${f.split('/').pop()} | ${data.filter(d=>d.loc==='en').map(d=>d.inventory[f]||0).join(' | ')} |`);await fs.writeFile(path.join(root,'00-setup.md'),`# Этап 0\nДата: 07.10.2026 (Europe/Moscow).\nHEAD: 0dda3387860b5cd49a8a5a296eb5d33824d03e06; ветка: codex/portfolio-integration-g.\nНезакоммиченных путей: 413; исходный status: logs/git-before.txt.\nСервер: ${base}; один процесс dev, сборка не запускалась.\nПрочитаны SWEEP-PROMPT.md, CLAUDE.md, CONTENT-RULES.md и распределение владельцев; CONTRACT — точечный поиск.\nHTTP: ${data.map(d=>`${d.loc}/${d.route}=${d.status}`).join(', ')}.\nИнвентарь — корни scoped CID в DOM, CID→файл из style[data-vite-dev-id]; это число DOM-корней, у многокорневого компонента может отличаться от числа вызовов.\nПолный EN/RU инвентарь: logs/setup.json.\nКартинок открыто: 0.\n\n| Компонент | About | Agent | Portal | Learn | Vet | Pawly | 404 |\n|---|---:|---:|---:|---:|---:|---:|---:|\n${rows.join('\n')}\n`);console.log(`Этап 0: ${data.length} маршрутов; HTTP ${data.filter(d=>d.status===200).length}/14 = 200; inventory ${components.length}; images 0; saved 00-setup.md`);}
async function auto(){const b=await launch(),out=[];const jobs=[];for(const loc of ['en','ru'])for(const route of routes)for(const width of [1440,360])jobs.push({route,loc,width});let index=0;await Promise.all([0,1].map(async()=>{const p=await b.newPage();for(;;){let i=index++;if(i>=jobs.length)break;let j=jobs[i];await p.setViewportSize({width:j.width,height:j.width===360?780:900});const response=await p.goto(urlFor(j.route,j.loc),{waitUntil:'networkidle'});await settle(p);let d=await p.evaluate(collect);out.push({...j,status:response.status(),...d});await fs.writeFile(path.join(root,'logs/sweep-partial.json'),JSON.stringify(out,null,2));if(out.length%7===0)console.log(`Collected ${out.length}/28`);}await p.close();}));await b.close();out.sort((a,b)=>a.route.localeCompare(b.route)||a.loc.localeCompare(b.loc)||b.width-a.width);await fs.writeFile(path.join(root,'logs/sweep.json'),JSON.stringify(out,null,2));const classes=['T1','T2','T3','T4','C1','C2','C3','L1','L2','L3','L4','L5','H1','H2','H3','K1','X1','X2','X3','I1','R1'];let lines=['# Этап 1 — автоматический сбор','28 состояний: 7 маршрутов × EN/RU × 1440×900 / 360×780. Картинок: 0.','Кандидаты не равны подтверждённым проблемам. Полные списки: logs/sweep.json.','Секции/медиа L4, headings H1/H3 и links K1 сохранены для сравнения.',''];for(const cls of classes){const all=out.flatMap(d=>d.candidates.filter(c=>c.cls===cls).map(c=>({...c,place:`${d.loc}/${d.route}@${d.width}`})));lines.push(`## ${cls}: ${all.length} автоматических кандидатов`);let grouped=new Map();for(const c of all){let g=grouped.get(c.component)||[];g.push(c);grouped.set(c.component,g);}for(const [comp,g] of grouped)lines.push(`- ${comp}: ${g.length}; ${[...new Set(g.map(c=>c.place))].join(', ')}; пример: ${g[0].text.slice(0,60)} ${JSON.stringify(g[0].detail).slice(0,160)}`);if(!all.length)lines.push('- Для визуальных/редакторских классов ноль здесь означает отложенную оценку; прочие — замер не дал кандидата.');}await fs.writeFile(path.join(root,'01-auto.md'),lines.join('\n')+'\n');for(const d of out.filter(d=>d.width===1440)){const name=d.route.replaceAll('/','-');await fs.mkdir(path.join(root,'logs/text'),{recursive:true});await fs.writeFile(path.join(root,`logs/text/${name}-${d.loc}.md`),`# ${d.loc}/${d.route}; редакционных слов: ${d.wordCount}\n`+d.copy.map(s=>`\n## ${s.selector}\n${s.text}\n\nAlt: ${s.alt.join(' | ')}\n`).join(''));}console.log(`Saved 01-auto.md; ${out.reduce((s,d)=>s+d.candidates.length,0)} candidates; images 0; internal links ${out.reduce((s,d)=>s+d.publicLinks.length,0)}`);}
if(process.argv[2]==='setup')await setup();if(process.argv[2]==='auto')await auto();
