import {root,base,routes,urlFor,launch,settle} from './sweep.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const sharp=createRequire('D:/Claude-projects/Site-portfolio/package.json')('sharp');
const ev=path.join(root,'evidence');
const data=JSON.parse(await fs.readFile(path.join(root,'logs/sweep.json'),'utf8'));
const mode=process.argv[2]||'overview';
const manifest=mode==='detail'?JSON.parse(await fs.readFile(path.join(root,'logs/evidence-manifest.json'),'utf8')):[];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;');
export async function sheet(items,name,{cols=2,w=780,h=650}={}){const rows=Math.ceil(items.length/cols),canvas=sharp({create:{width:cols*w,height:rows*h,channels:3,background:'#d8d8d8'}});let comps=[];for(let i=0;i<items.length;i++){let it=items[i],buf=it.buffer||await fs.readFile(it.file);let out=await sharp(buf).resize({width:w-16,height:h-44,fit:'inside',withoutEnlargement:true}).toBuffer();let m=await sharp(out).metadata();let x=(i%cols)*w,y=Math.floor(i/cols)*h;comps.push({input:out,left:x+8,top:y+36});comps.push({input:Buffer.from(`<svg width="${w}" height="32"><rect width="100%" height="100%" fill="#fff"/><text x="8" y="21" font-size="15" font-family="Arial">${esc(it.label)}</text></svg>`),left:x,top:y});}await canvas.composite(comps).png().toFile(path.join(ev,name));manifest.push({file:name,items:items.map(i=>i.label),width:cols*w,height:rows*h});}
const b=await launch(),p=await b.newPage({viewport:{width:1440,height:900}});
if(mode==='overview'){
for(const route of routes){await p.goto(urlFor(route,'en'),{waitUntil:'networkidle'});await settle(p);let name=route.replaceAll('/','-')+'-en-1440-full.png';await p.screenshot({path:path.join(ev,name),fullPage:true});manifest.push({file:name,route,loc:'en',width:1440,state:'networkidle/fonts/3s/scroll400-100ms/2s'});console.log('Captured '+route);}
await p.goto(base+'/',{waitUntil:'networkidle'});await settle(p);await p.screenshot({path:path.join(ev,'home-en-1440-reference.png'),fullPage:true});
const six=routes.filter(r=>r!=='404').map(r=>({file:path.join(ev,r.replaceAll('/','-')+'-en-1440-full.png'),label:r}));
await sheet(six.slice(0,3),'overview-A-en-1440.png',{cols:3,w:500,h:2380});await sheet(six.slice(3),'overview-B-en-1440.png',{cols:3,w:500,h:2380});await sheet([{file:path.join(ev,'home-en-1440-reference.png'),label:'Home reference; not audited'}],'home-reference-sheet.png',{cols:1,w:500,h:2380});
await b.close();await fs.writeFile(path.join(root,'logs/evidence-manifest.json'),JSON.stringify(manifest,null,2));console.log('Overview saved; images opened 0');process.exit(0);
}
// Candidate-only crops, positions come from the frozen automatic measurement.
const targets=JSON.parse(await fs.readFile(path.join(root,'logs/visual-targets.json'),'utf8'));
let items=[];for(const t of targets.filter(x=>x.width===1440&&x.loc==='en')){const file=path.join(ev,t.route.replaceAll('/','-')+'-en-1440-full.png'),m=await sharp(file).metadata();const left=Math.max(0,Math.min(m.width-1,Math.round(t.rect.x))),top=Math.max(0,Math.min(m.height-1,Math.round(t.rect.y)-20));const width=Math.min(900,m.width-left,Math.max(360,Math.round(t.rect.w))),height=Math.min(600,m.height-top,Math.max(180,Math.round(t.rect.h)+40));const buffer=await sharp(file).extract({left,top,width,height}).png().toBuffer();let name=`${t.route.replaceAll('/','-')}-${t.loc}-${t.width}-${t.id}.png`;await fs.writeFile(path.join(ev,name),buffer);items.push({buffer,label:`${t.id} ${t.route} ${t.selector||''}`});manifest.push({file:name,target:t,clip:{left,top,width,height}});}
for(let i=0;i<items.length;i+=4)await sheet(items.slice(i,i+4),`candidates-desktop-${i/4+1}.png`,{cols:2,w:780,h:645});
let mobile=[];for(const [key,ts] of Object.entries(Object.groupBy(targets.filter(x=>x.width===360),t=>`${t.loc}/${t.route}`))){let t=ts[0];await p.setViewportSize({width:360,height:780});await p.goto(urlFor(t.route,t.loc),{waitUntil:'networkidle'});await settle(p);let name=t.route.replaceAll('/','-')+`-${t.loc}-360-full.png`;await p.screenshot({path:path.join(ev,name),fullPage:true});let m=await sharp(path.join(ev,name)).metadata();for(const a of ts){const top=Math.max(0,Math.min(m.height-1,Math.round(a.rect.y)-20)),height=Math.min(600,m.height-top,Math.max(240,Math.round(a.rect.h)+40));let buffer=await sharp(path.join(ev,name)).extract({left:0,top,width:360,height}).png().toBuffer();await fs.writeFile(path.join(ev,`${a.route.replaceAll('/','-')}-${a.loc}-360-${a.id}.png`),buffer);mobile.push({buffer,label:`${a.id} ${key} 360`});}manifest.push({file:name,route:t.route,loc:t.loc,width:360});}
for(let i=0;i<mobile.length;i+=6)await sheet(mobile.slice(i,i+6),`candidates-mobile-${i/6+1}.png`,{cols:3,w:400,h:645});
await p.setViewportSize({width:1440,height:900});let choice=data.filter(d=>d.loc==='en'&&d.width===1440&&d.route.startsWith('work/')).sort((a,b)=>b.links.length-a.links.length)[0];await p.goto(urlFor(choice.route,'en'),{waitUntil:'networkidle'});await settle(p);let focus=[],seen=new Set();for(let i=0;i<70&&focus.length<6;i++){await p.keyboard.press('Tab');let a=await p.evaluate(()=>{let e=document.activeElement,r=e.getBoundingClientRect(),s=getComputedStyle(e);return{tag:e.tagName,text:e.innerText?.trim().slice(0,60),href:e.getAttribute('href'),class:e.className,rect:{x:r.x,y:r.y,w:r.width,h:r.height},outline:s.outline,shadow:s.boxShadow,focus:e.matches(':focus-visible'),inline:!!e.closest('p')};});if(a.tag==='A'&&!a.inline&&a.rect.w&&a.rect.h&&!seen.has(a.href)&&!a.href?.includes('#main')){seen.add(a.href);let x=Math.max(0,Math.min(540,Math.round(a.rect.x)-30)),y=Math.max(0,Math.min(300,Math.round(a.rect.y)-70));let buffer=await p.screenshot({clip:{x,y,width:900,height:600}});let name=`${choice.route.replaceAll('/','-')}-en-1440-focus-${focus.length+1}.png`;await fs.writeFile(path.join(ev,name),buffer);focus.push({buffer,label:`Tab ${i+1}: ${a.text} ${a.outline}`});manifest.push({file:name,focus:a});}}
await sheet(focus,'focus-cta-sheet.png',{cols:2,w:780,h:645});
await p.emulateMedia({reducedMotion:'reduce'});await p.goto(urlFor('work/agent-ops-console','en'),{waitUntil:'networkidle'});await settle(p);let reduced=await p.screenshot({clip:{x:40,y:100,width:900,height:600}});await fs.writeFile(path.join(ev,'work-agent-ops-console-en-1440-cover-reduced.png'),reduced);let normal=await sharp(path.join(ev,'work-agent-ops-console-en-1440-full.png')).extract({left:40,top:100,width:900,height:600}).toBuffer();await sheet([{buffer:normal,label:'Agent cover — normal final state'},{buffer:reduced,label:'Agent cover — reduced motion final state'}],'motion-final-sheet.png',{cols:2,w:780,h:645});
await b.close();await fs.writeFile(path.join(root,'logs/evidence-manifest.json'),JSON.stringify(manifest,null,2));console.log(`Evidence complete; ${manifest.length} files/records; no images opened by capture script`);
